# Generated by Django 4.2.6 on 2024-01-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default='xd', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default='xdxd', max_length=255),
            preserve_default=False,
        ),
    ]
