# Generated by Django 4.2.6 on 2024-01-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumbers_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('jd_organizcyjnej', models.CharField(max_length=255)),
                ('lokalizacja', models.CharField(max_length=255)),
                ('num_wew', models.CharField(max_length=255)),
                ('num_tel', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Clinic',
        ),
    ]
