# Generated by Django 4.2.6 on 2023-12-11 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodphoto',
            name='digest',
            field=models.CharField(choices=[('latwo', 'Łatwostrawna'), ('podst', 'Podstawowa')], default=('latwo', 'Łatwostrawna'), max_length=20),
        ),
        migrations.AlterField(
            model_name='foodphoto',
            name='image',
            field=models.ImageField(upload_to='uploads/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='foodphoto',
            name='type',
            field=models.CharField(choices=[('kolacja', 'Kolacja'), ('obiad', 'Obiad'), ('śniadanie', 'Śniadanie')], default=('obiad', 'Obiad'), max_length=20),
        ),
    ]
