# Generated by Django 4.2.6 on 2023-12-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_resize', '0002_foodphoto_digest_alter_foodphoto_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodphoto',
            name='digest',
            field=models.CharField(choices=[('latwo', 'Łatwostrawna'), ('podst', 'Podstawowa')], default='latwo', max_length=20),
        ),
        migrations.AlterField(
            model_name='foodphoto',
            name='type',
            field=models.CharField(choices=[('kolacja', 'Kolacja'), ('obiad', 'Obiad'), ('sniadanie', 'Śniadanie')], default='obiad', max_length=20),
        ),
    ]
